### ISSUE TITLE
[Feature] 테스트 데이터 생성

### ISSUE THREAD

**Issue by jw-jin** [2023Summer/mr-playlist-backend#37]
## Description
테스트를 위한 데이터 추가 및 Mock data 생성 자동화
### To-do
 - [x] 테스트 데이터 추가
 - [x] Mock data 생성 자동화

**Comment by shinb-bong** [comment]
제 테스트 데이터는 언제 어떻게 드리면될까요?
@jw-jin

**Comment by jw-jin** [comment]
> 제 테스트 데이터는 언제 어떻게 드리면될까요? @jw-jin

슬랙으로 보내주시면 됩니다!
