### ISSUE TITLE
[Notice] Develop 브랜치 생성 및 디폴트 설정

### ISSUE THREAD

**Issue by shinb-bong** [2023Summer/mr-playlist-backend#54]
## Description
이번에 충돌을 처리하다가 
개발 브랜치가 하나 있고 운영브랜치는 최종 배포 일때만 사용해야할듯합니다.

main에서 충돌을 잘못 처리하거나 커밋 이력 관리하는데 
현재 깃플로우는 애매한 위치에 있는것 같습니다.
 
디폴트 설정을 진행하겠습니다.

**모두 comment 가 달릴때까지 해당 이슈는 지속하겠습니다.**
기능 추가 및 파일 추가

### To-do

- [x] develop 브랜치 생성
- [x] 규칙 수정
- [x] default 설정

/* 브랜치 생성시 feature/#{이슈번호} 형식 작성 */

**Comment by jw-jin** [comment]
확인했습니다. 그럼 main 브랜치를 운영 브랜치로 사용하는 건가요?

**Comment by shinb-bong** [comment]
넵 그렇습니당
